services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      # Only will build development stage from our dockerfile
      target: development
    env_file:
        - .env
    volumes:
      - .:/usr/src/app
    # Run in dev Mode: npm run start:dev
    command: npm run start:dev
    ports:
      - 3000:3000
    depends_on:
      - redis
      - mongodb
      - rabbitmq
  redis: # Name of container
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    volumes: 
      - redis:/data
  mongodb:
    image: mongo:5.0.0
    container_name: mongodb
    volumes:
      - ./database:/data/db
    ports:
      - 27017:27017
    restart: always
  rabbitmq:
    image: rabbitmq:3.9.2-management
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - rabbitmq:/data
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  docker-nest-postgres:
  rabbitmq:
  redis:
    driver: local